// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2W705lq4shuQxre5CwNhzJScHcsp2kbQ',
    appId: '1:1068107148433:web:879ba27e58203dff4b2330',
    messagingSenderId: '1068107148433',
    projectId: 'sippa-bb964',
    authDomain: 'sippa-bb964.firebaseapp.com',
    databaseURL:
        'https://sippa-bb964-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sippa-bb964.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkv0VOwhL0t9pwQKN-E27F9FYI4cRNRo',
    appId: '1:1068107148433:android:fa46d52d073c44e24b2330',
    messagingSenderId: '1068107148433',
    projectId: 'sippa-bb964',
    databaseURL:
        'https://sippa-bb964-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sippa-bb964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvKSnUomaH2m8o8fJuxAOFMkrHNrRUG7E',
    appId: '1:1068107148433:ios:661b3e1c6961a6244b2330',
    messagingSenderId: '1068107148433',
    projectId: 'sippa-bb964',
    databaseURL:
        'https://sippa-bb964-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sippa-bb964.firebasestorage.app',
    iosBundleId: 'com.example.sippaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvKSnUomaH2m8o8fJuxAOFMkrHNrRUG7E',
    appId: '1:1068107148433:ios:661b3e1c6961a6244b2330',
    messagingSenderId: '1068107148433',
    projectId: 'sippa-bb964',
    databaseURL:
        'https://sippa-bb964-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sippa-bb964.firebasestorage.app',
    iosBundleId: 'com.example.sippaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2W705lq4shuQxre5CwNhzJScHcsp2kbQ',
    appId: '1:1068107148433:web:f5d10dd4cc8abc364b2330',
    messagingSenderId: '1068107148433',
    projectId: 'sippa-bb964',
    authDomain: 'sippa-bb964.firebaseapp.com',
    databaseURL:
        'https://sippa-bb964-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sippa-bb964.firebasestorage.app',
  );
}
